# Utils

In [28]:
import torch
import matplotlib.pyplot as plt
import pandas as pd
from torch.nn import Sigmoid


# Initial Data

In [40]:
X = torch.tensor([
        [1.0, 35.0, 50],
        [1.0, 40.0, 53],
        [1.0, 25.0, 80],
        [1.0, 28.0, 73]
    ])

t_p = torch.tensor([
        [1.0],
        [1.0],
        [-1.0],
        [-1.0]
    ])

t_lr = torch.tensor([
        [1.0],
        [1.0],
        [0.0],
        [0.0]
    ])

w = torch.tensor([
        [0.3],
        [0.2],
        [0.25]
    ])

In [30]:
#class Visualization :


# Perceptron Algorithm

In [41]:
class Perceptron:

    def forward(self, X : torch.Tensro, w : torch.Tensor):
        return torch.sign(X @ w)

    def gradient(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        perceptron_criteria = (X @ w) * t
        mask = (perceptron_criteria <= 0).squeeze()

        U = X[mask]
        t_U = t[mask]

        return (U * t_U).sum(dim=0).view(-1, 1)

    def error(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        #return torch.mean((self.forward(X, w) - t) ** 2)
        return (t - self.forward(X, w)).abs().mean()

    def accuracy(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        return (self.forward(X, w) == t).float().mean()

    def train(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor, iterations : int, alpha : float):
        history_error = []
        for i in range(iterations):
            history_error.append(self.error(X,w,t).item())
            delta = self.gradient(X, w, t)
            w = w + alpha * delta

        return w, history_error

perceptron = Perceptron()
weights_perceptron , history_error_perceptron = perceptron.train(X, w, t_p, 100, 1)
print(weights_perceptron, '\n', history_error_perceptron)
print(perceptron.forward(X, weights_perceptron))


tensor([[   4.3000],
        [ 301.2000],
        [-136.7500]]) 
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
tensor([[ 1.],
        [ 1.],
        [-1.],
        [-1.]])


# Logistic Regression

In [42]:
class LogisticRegression:

    def __init__(self):
        self.sigmoid = Sigmoid()

    def forward(self, X : torch.Tensor, w : torch.Tensor):
        return self.sigmoid(X @ w)

    def gradient(self, X :torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        diff = (X * (t - self.forward(X, w))).sum(dim=0)
        return diff.view(-1, 1) / X.shape[0]

    def medium_absolute_error(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        return (t - self.forward(X, w)).abs().mean()

    def accuracy(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor):
        return (self.forward(X, w) == t).float().mean()

    def train(self, X : torch.Tensor, w : torch.Tensor, t : torch.Tensor, iterations : int, alpha : float):
        history_error = []
        for i in range(iterations):
            history_error.append(self.medium_absolute_error(X, w, t).item())
            delta = self.gradient(X, w, t)
            w = w + alpha * delta

        return w, history_error

logistic_regression = LogisticRegression()
weights_logistic_regression , history_error_logistic_regression = logistic_regression.train(X, w, t_lr, 100, 1)
print(weights_logistic_regression, '\n', history_error_logistic_regression)
print(logistic_regression.forward(X, weights_logistic_regression))

tensor([[  1.2525],
        [ 70.5124],
        [-31.0502]]) 
 [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.25, 0.5, 0.5, 0.5, 0.2975022792816162, 0.5, 0.5, 0.5, 0.25, 0.24999991059303284, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
tensor([[1.],
        [1.],
        [0.],
        [0.]])
